force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Convenience_Package__c.field-meta.xml
<CustomField>
    <label>Convenience Package</label>
    <type>Checkbox</type>
    <fullName>Convenience_Package__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Engine__c.field-meta.xml
<CustomField>
    <fullName>Engine__c</fullName>
    <label>Engine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T5 FWD</fullName>
            </value>
            <value>
                <fullName>T5 AWD</fullName>
            </value>
            <value>
                <fullName>T6 AWD</fullName>
            </value>
            <value>
                <fullName>T8 eAWD Plug-in Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Hybrid__c.field-meta.xml
<CustomField>
    <label>Hybrid</label>
    <type>Checkbox</type>
    <fullName>Hybrid__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Interior__c.field-meta.xml
<CustomField>
    <fullName>Interior__c</fullName>
    <label>Interior</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amber Leather in Charcoal</fullName>
            </value>
            <value>
                <fullName>Blond Leather in Blond/Charcoal Interior</fullName>
                <default>true</default>
                <label>Blond Leather in Blond/Charcoal Interior</label>
            </value>
            <value>
                <fullName>Charcoal Leather in Charcoal Interior</fullName>
            </value>
            <value>
                <fullName>Amber Nappa Leaher w/ Contour Seats in Charcoal Interior</fullName>
            </value>
            <value>
                <fullName>Blond Leather w/ Contour Seats in Blond/Charcoal Interior</fullName>
            </value>
            <value>
                <fullName>Charcoal Nappa Leather w/ Contour Seats in Charcoal Interior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <defaultValue>&#39;Flash&#39;</defaultValue>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S90</fullName>
            </value>
            <value>
                <fullName>S60</fullName>
            </value>
            <value>
                <fullName>XC90</fullName>
            </value>
            <value>
                <fullName>XC60</fullName>
            </value>
            <value>
                <fullName>XC40</fullName>
            </value>
            <value>
                <fullName>V90 Cross Country</fullName>
            </value>
            <value>
                <fullName>V90</fullName>
            </value>
            <value>
                <fullName>V60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Momentum_Plus_Package__c.field-meta.xml
<CustomField>
    <label>Momentum Plus Package</label>
    <type>Checkbox</type>
    <fullName>Momentum_Plus_Package__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Protection_Package_Premier__c.field-meta.xml
<CustomField>
    <label>Protection Package Premier</label>
    <type>Checkbox</type>
    <fullName>Protection_Package_Premier__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Wheels__c.field-meta.xml
<CustomField>
    <fullName>Wheels__c</fullName>
    <label>Wheels</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>19" 10-Spoke Turbine Silver Bright Alloy Wheels</fullName>
                <default>true</default>
                <label>19" 10-Spoke Turbine Silver Bright Alloy Wheels</label>
            </value>
            <value>
                <fullName>20" 5-Double Spoke Matte Tech Black Alloy Wheels</fullName>
            </value>
            <value>
                <fullName>21” 5 V-Spoke Black Diamond Cut Alloy Wheels</fullName>
            </value>
            <value>
                <fullName>22" 6-Double Spoke Matte Tech Black Diamond Cut Alloy Wheels w/Summer Performance Tires*</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/sampleDataCreation.cls
public with sharing class sampleDataCreation {

    public static void createData() {
        account a = new account();
        a.Name= 'Volvo Cars of The Woodlands';
        a.Phone= '888-728-7147';
        a.Website= 'http://www.volvocarswoodlands.com/';
        a.BillingStreet= '16785A Interstate 45 South';
        a.BillingPostalCode= '77385';
        a.BillingCity= 'The Woodlands';
        a.BillingState= 'TX';
        a.BillingCountry= 'USA';
        a.ShippingStreet= '16785A Interstate 45 South';
        a.ShippingCity= 'The Woodlands';
        a.ShippingState= 'TX';
        a.ShippingCountry= 'USA';
        a.ShippingPostalCode= '77385';

        insert a;


        contact c = new contact();
        c.FirstName = 'Jodi';
        c.LastName = 'Innerfield';
        c.Email = 'jinnerfield@salesforce.com';
        c.MobilePhone = '415-622-8174';

        insert c;

        Vehicle__c v = new Vehicle__c();
        v.Convenience_Package__c = true;
        v.Engine__c = 'T5 FWD';
        v.Dealer__c = a.Id;
        v.Owner__c = c.Id;
        v.Hybrid__c = false;
        v.Interior__c = 'Blond Leather in Blond/Charcoal Interior';
        v.Model__c = 'XC90';
        v.Momentum_Plus_Package__c = false;
        v.Paint__c = '0';
        v.Protection_Package_Premier__c = false;
        v.Status__c = 'Evaluation';
        v.Wheels__c = '20\" 5-Double Spoke Matte Tech Black Alloy Wheels';
        v.Year__c = '2018';

        insert v;

        Event e = new Event();
        e.WhatId = v.Id;
        e.WhoId = c.Id;
        e.StartDateTime = system.now().addDays(5).addMinutes(System.now().minute() * -1);
        e.Subject = 'Test Drive for Jodi';
        e.EndDateTime = e.StartDateTime.addHours(1);

        insert e;


    }


}